Add CI optimizations for training tasks
mozilla/firefox-translations-training pull request #240
Opened 2023-11-01 15:08 UTC by gregtatum

I believe this will prevent CI from running training tasks when touching other folders.

2023-11-01 15:08 UTC, gregtatum commented on taskcluster/ci/tests/kind.yml
> +            - pipeline/**
@eu9ene Please double check that I'm covering the required folders here and above.

2023-11-01 15:25 UTC, gregtatum commented
I guess the only way to test this is to merge it since I'm touching the taskcluster file here.

2023-11-01 18:17 UTC, eu9ene reviewed
Can we add this optimization to the main Taskcluster CI pipeline run? So that it doesn't rerun if we change anything except the pipeline and taskcluster dirs?

2023-11-01 18:17 UTC, eu9ene commented on taskcluster/ci/tests/kind.yml
> +            - envs/**
envs and configs are currently used only for snakemake

2023-11-01 20:00 UTC, bhearsum requested changes
> Can we add this optimization to the main Taskcluster CI pipeline run? So that it doesn't rerun if we change anything except the pipeline and taskcluster dirs?

Big +1. This is done with the `run-on-tasks-for` in https://github.com/mozilla/firefox-translations-training/blob/1d1b4922bbc5f18e312446a8897b7fae42bd5376/taskcluster/ci/all/kind.yml#L34, so adding an `optimization` there would most likely do it.

However...this would also cause real training runs to get optimized away unless they're on a branch that happens to modify one of the `pipeline` or `taskcluster` files (which is not a guarantee, especially after the pipeline has stabilized more).

My suggestion would to add a `all-pr` entry in `all/kind.yml`, and have that run on PRs with this optimization, and then `all` can be saved for real training runs. (Make sure you update `stage` otherwise both will fire in real training runs.

2023-11-14 17:51 UTC, gregtatum commented
> Can we add this optimization to the main Taskcluster CI pipeline run? So that it doesn't rerun if we change anything except the pipeline and taskcluster dirs?

I'd like this to be a follow-up unless this is actually blocking this PR. I'm low-context on this repo, especially after spending a couple of months working on Gecko stuff. It will take me a bit to get back up to speed on how everything works, and this seems mergeable with @eu9ene 's suggestion addressed.

2023-11-14 17:56 UTC, bhearsum approved these changes

2023-11-14 18:56 UTC, eu9ene approved these changes

2023-11-14 21:02 UTC, merged