fix(splitter): properly support gzip
mozilla/firefox-translations-training pull request #361
Opened 2024-01-12 08:20 UTC by AmitMY

splitter does not support gzip, related to #340

2024-01-12 17:39 UTC, eu9ene commented
> splitter does not support gzip, related to #340
> 
> and I would appreciate help for the rest of the issue.

I think we never supported gzip in the pipeline. The alternative compression tool to `zstd` is `pigz` which is parallel gzip and a lot faster on big datasets. Please check if it works for you.

2024-01-12 19:44 UTC, AmitMY commented
The code here says `gzip` as a possible compression command:
https://github.com/mozilla/firefox-translations-training/pull/361/files#diff-37d52397e2d0d58bc72c90f12431a82e8a0cb06e5fc7fe34a3c139a5d82148c8R89
In any case, `pigz` also does not support `--rm`, so I updated the code to support it

2024-01-12 20:30 UTC, eu9ene requested changes

2024-01-12 20:30 UTC, eu9ene commented on pipeline/translate/splitter.py
We should just do `os.remove` to unify the behavior across the differnet tools or even better 
```
if os.path.isfile(current_name):
  os.remove(current_name)
```

The idea is not to keep compressed and uncompressed files on disk since the can be huge

2024-01-13 08:14 UTC, AmitMY commented on pipeline/translate/splitter.py
done

2024-01-15 17:37 UTC, eu9ene approved these changes

2024-01-15 17:37 UTC, eu9ene commented on pipeline/translate/splitter.py
> +    # gzip and pigz remove the file by default, but zstd does not
thanks for the comment, now it's clear what's going on here

2024-01-15 17:50 UTC, eu9ene commented
@AmitMY could you commit a small change to retrigger CI? I disabled it temporarily no to run the whole pipeline on each commit and now enabled again.

2024-01-15 17:52 UTC, eu9ene commented
Also snakemake dry-run got broken and now disabled so it might be worth looking into https://github.com/mozilla/firefox-translations-training/issues/363

2024-01-16 21:48 UTC, merged