Override W&B data on a resumed training
mozilla/firefox-translations-training pull request #595
Opened 2024-05-14 13:56 UTC by vrigal

Closes #594

2024-05-14 17:53 UTC, eu9ene requested changes

2024-05-14 17:53 UTC, eu9ene commented on tracking/translations_parser/publishers.py
> +                        run.delete()
@vrigal it's not supposed to delete the data from the previous run. It should continue tracking like the restart never happened.

2024-05-14 18:00 UTC, eu9ene commented on tracking/translations_parser/publishers.py
> +                        run.delete()
See https://docs.wandb.ai/guides/runs/resuming#resuming-guidance

2024-05-15 10:46 UTC, vrigal commented
I applied the changes (to resume an existing run on W&B) and tested here: https://wandb.ai/teklia/test/runs/tv2vtdha

> we can just pass the artifacts dir to the script parse_tc_logs --from-stream -v --wandb-artifacts ${model_dir}.

Its probably worth opening an issue for this. W&B seems to sync (override) logs & artifacts automatically. (https://wandb.ai/teklia/test/groups/test/files/output.log).

> One complication here is that we continue training from the last checkpoint so there will be small overlap with previously written data

W&B should handle this automatically, as it ignores data with a step inferior the last data written.
I think it should simply trigger some warnings from the W&B client.

2024-05-15 17:42 UTC, eu9ene commented
@vrigal one thing I don't understand is who sets "RUN_ID" env?

2024-05-15 18:35 UTC, eu9ene approved these changes
Ok, this can work but from the code perspective there are some issues:
- w&b publisher should not know anything about Taskcluster environment variables
- why don't we just use resume="allow" so that if the run already exists, it continues automatically? I don't think there is a use case where we have a run with the same name when running things on Taskcluster except the restart of the same task. I guess this logic was implemented in the publisher for publishing offline experiments to prevent republishing the same ones. In this case, the publisher should accept an argument set by a cli that indicates what to do if the run already exists.
 
Other known issues:
- W&B drops overlapped data from the new run instead of overwriting (`wandb: WARNING (User provided step: 15000 is less than current step: 15001. Dropping entry: {'gnorm': 0.7161, '_timestamp': 1715790811.6654584}). `)

I think since it kind of works we can merge it to unblock enabling spot instances but we should address those issues later.

2024-05-15 18:35 UTC, merged

2024-05-16 06:57 UTC, vrigal commented
> why don't we just use resume="allow" so that if the run already exists, it continues automatically? I don't think there is a use case where we have a run with the same name when running things on Taskcluster except the restart of the same task. I guess this logic was implemented in the publisher for publishing offline experiments to prevent republishing the same ones. In this case, the publisher should accept an argument set by a cli that indicates what to do if the run already exists.

This is an old issue. The simpler way to handle this would be to use `<group>-<model>` as a unique ID in W&B.
It should be possible to keep  resume="allow" then. It would be compatible with the override option and would probably work in most case (W&B drops overlapped data, as you mentioned), but requires some important changes in the code.

2024-05-16 16:44 UTC, eu9ene commented
> > why don't we just use resume="allow" so that if the run already exists, it continues automatically? I don't think there is a use case where we have a run with the same name when running things on Taskcluster except the restart of the same task. I guess this logic was implemented in the publisher for publishing offline experiments to prevent republishing the same ones. In this case, the publisher should accept an argument set by a cli that indicates what to do if the run already exists.
> 
> This is an old issue. The simpler way to handle this would be to use `<group>-<model>` as a unique ID in W&B. It should be possible to keep resume="allow" then. It would be compatible with the override option and would probably work in most case (W&B drops overlapped data, as you mentioned), but requires some important changes in the code.

We can rethink all that in #408, but I would use UID in model names as a last resort because they would clutter the dashboards.

2024-05-17 09:34 UTC, vrigal commented
@eu9ene to be clear, run ID (used to identify a run) is different that run name (used to display graphs). For now we do not use an ID, it is automatically set by W&B (e.g. `brmhnekj`) which guarantees unicity. But if there is a unique way to identify a run (e.g. `<group>-<model_name>`) it could help with deletion(override) or resuming a run. It can be a separate issue than #408. I'll write an issue for this.